### ISSUE TITLE
Divide inequality index by average price in a city

### ISSUE THREAD

**Issue by n-kb** [jplusplus/rentswatch-api#1]
Right now, the inequality index is a function of the average price (the higher the price, the higher the absolute variations). The plots inequality index (x) with average price.

![get-scatterplot](https://cloud.githubusercontent.com/assets/864677/13729438/8fb18f10-e935-11e5-92ab-edaf32447847.png)

We should divide the index by the average price for the city to remove this bias.

**Comment by pirhoo** [comment]
It gives me:
- Paris: 0.2023805067487303
- Berlin: 0.14235581181468893
- Ostrava: 0.286945509338521

Does it sound correct?

**Comment by n-kb** [comment]
Yes. Now I need to find the right radius for each city.
